from __future__ import annotations


def _lines(*rows: str) -> str:
    return "\n".join(row for row in rows if row.strip())


DEFAULT_LOUNGE_PROFILE_DRAFTS: dict[str, dict[str, str]] = {
    "secret_yauza": {
        "tagline": "Камерный lounge на Яузской, 5 с приватными комнатами и длинной вечерней посадкой.",
        "summary": "По Menzy и where2smoke Secret Lounge Yauza работает как городской lounge-спот с двумя VIP-комнатами, парковкой по звонку и кальянами от 1300₽. Для app это хороший профиль места, вокруг которого можно строить подборки миксов, брендовые сторис и будущие партнёрские кампании.",
        "logo_image_url": "",
        "hero_image_url": "https://razmarin.menzy.ru/v1/storage/buckets/images/files/68717063002bcf95246a/preview?width=1200&height=600&gravity=center&output=png&project=menzy",
        "venue_address": "Яузская ул., 5, БЦ «Яузская 5»",
        "venue_hours": "Пн-Чт, Вс 14:00-03:00 · Пт-Сб до 04:00",
        "venue_price": "от 1300₽",
        "venue_format": "2 VIP · приватный lounge · парковка",
        "venue_phone": "",
        "venue_booking_url": "https://menzy.ru/secretyauza?ysclid=mn767mnk9x929861929",
        "venue_menu_url": "",
        "venue_loyalty_title": "Secret Guest",
        "venue_loyalty_summary": "Чем чаще заходишь в lounge, тем выше персональная скидка и приоритет на вечерние посадки.",
        "highlights_text": _lines("VIP", "Приватно", "Парковка"),
        "articles_text": _lines(
            "Формат | VIP-комнаты и приватный формат | Две отдельные комнаты под компанию и более закрытую вечернюю посадку. | https://where2smoke.net/img/Moscow/gallerysecret/1391015_6.jpg",
            "Сервис | Парковка и сервис по звонку | Заведение делает ставку на спокойный сервис, приватность и длинную lounge-сессию. | https://where2smoke.net/img/Moscow/gallerysecret/1391034_0.jpg",
        ),
        "menu_highlights_text": _lines(
            "Signature lounge | Спокойная приватная посадка под долгую сессию.",
            "VIP-комнаты | Отдельные комнаты под компанию и поздний вечер.",
            "Вечерний формат | Поздняя посадка, приватный сервис и длинный lounge-сценарий.",
        ),
        "service_cards_text": _lines(
            "Открыть карточку lounge | Контакты, адрес и быстрый вход в место. | https://menzy.ru/secretyauza?ysclid=mn767mnk9x929861929",
        ),
    },
    "hookahplace_mars": {
        "tagline": "Круглосуточный гастро-lounge на Маросейке с VIP-зоной, авторской кухней и сильным ночным вайбом.",
        "summary": "По официальной странице HookahPlace MARS это круглосуточное гастро-пространство в центре Москвы, где кальянный отдых собран вместе с кухней, баром, DJ-сетами и приватной VIP-зоной. Для app это сильный lounge-профиль с ясным сценарием брони, меню и loyalty-слоя.",
        "logo_image_url": "https://api.russianhookah.ru/wp-content/uploads/2024/01/hp_mars_logo.png",
        "hero_image_url": "https://api.russianhookah.ru/wp-content/uploads/2024/01/img_0264-hdr.jpg",
        "venue_address": "Москва, ул. Маросейка, 7/8 c.1",
        "venue_hours": "Круглосуточно",
        "venue_price": "по брони",
        "venue_format": "VIP · кухня · бар · спорт",
        "venue_phone": "+7 977 321-21-21",
        "venue_booking_url": "https://hookahplace.ru/places/hookahplace-marosejka/?ysclid=mn7e94cccl52047423",
        "venue_menu_url": "https://hp-mars.ru",
        "venue_loyalty_title": "MARS Guest Pass",
        "venue_loyalty_summary": "Локальная loyalty-карта lounge: чем больше визитов, тем выше скидка на стол, приоритет на VIP и доступ к спецпредложениям.",
        "highlights_text": _lines("24/7", "Кухня", "VIP"),
        "articles_text": _lines(
            "Новости | Круглосуточный lounge-ритм | HookahPlace MARS держит формат 24/7 и собирает вокруг этого ночной сценарий заведения. | https://api.russianhookah.ru/wp-content/uploads/2024/01/img_0264-hdr.jpg",
            "Меню | Кухня, бар и сезонные позиции | Вместо чисто кальянного формата место подаётся как полноценный gastro-lounge с меню и баром. | https://api.russianhookah.ru/wp-content/uploads/2024/01/img_0264-hdr.jpg",
            "Акции | VIP и бонусы для постоянных гостей | Отдельная зона, вечерний формат и loyalty-подача хорошо ложатся в раздел спецпредложений заведения. | https://api.russianhookah.ru/wp-content/uploads/2024/01/hp_mars_logo.png",
        ),
        "menu_highlights_text": _lines(
            "Европейская кухня | База меню с гастро-подачей и авторскими акцентами.",
            "Паназиатские техники | Сильный вкусовой акцент для позднего ужина и компании.",
            "Авторские коктейли | Алкогольные и безалкогольные позиции под вечерний ритм.",
            "Сезонные предложения | Спецпредложения от шефа и событийные подачи.",
        ),
        "service_cards_text": _lines(
            "Забронировать стол | Прямой вход в официальную страницу брони. | https://hookahplace.ru/places/hookahplace-marosejka/?ysclid=mn7e94cccl52047423",
            "Меню и бар | Открыть сайт заведения и посмотреть формат кухни. | https://hp-mars.ru",
            "Позвонить | +7 977 321-21-21 | tel://79773212121",
            "VIP и вечеринки | Ночная программа, DJ и приватная зона. | https://hookahplace.ru/places/hookahplace-marosejka/?ysclid=mn7e94cccl52047423",
        ),
    },
    "hookahplace_vdnh": {
        "tagline": "Большой lounge у колеса обозрения «Солнце Москвы» с верандой, VIP-комнатами, двумя барами и караоке.",
        "summary": "По официальному сайту HookahPlace VDNH это крупное заведение у ВДНХ с панорамным видом, летней верандой, двумя этажами, тремя VIP-комнатами, авторской кухней и собственным loyalty welcome-бонусом. Для app это сильный lounge-профиль с ясными блоками меню, сервиса и акций.",
        "logo_image_url": "https://static.tildacdn.com/tild3363-3030-4533-b631-623237633962/Layer_8_.png",
        "hero_image_url": "https://static.tildacdn.com/tild6239-6439-4265-b663-373031366132/DSC08521_1.jpg",
        "venue_address": "Москва, 2-я Останкинская ул., 3",
        "venue_hours": "Вс-Чт 13:00-02:00 · Пт-Сб 13:00-05:00",
        "venue_price": "депозит по зонам",
        "venue_format": "2 этажа · веранда · 3 VIP · караоке",
        "venue_phone": "+7 495 108-27-07",
        "venue_booking_url": "https://hp-vdnh.ru/",
        "venue_menu_url": "https://hp-vdnh.ru/menu",
        "venue_loyalty_title": "VDNH Guest Card",
        "venue_loyalty_summary": "После регистрации lounge даёт 300 welcome-бонусов, а дальше удерживает гостя через визиты, посадку и формат зон.",
        "highlights_text": _lines("Веранда", "VIP", "Караоке"),
        "articles_text": _lines(
            "Акции | 300 приветственных бонусов за регистрацию | На главной странице заведение сразу выводит welcome-оффер в своей системе лояльности. | https://static.tildacdn.com/tild6239-6439-4265-b663-373031366132/DSC08521_1.jpg",
            "Новости | Веранда, VIP и вид на ВДНХ | Большая terrace, три VIP-комнаты, проектор на втором уровне и сценарий для мероприятий. | https://static.tildacdn.com/tild3532-3963-4133-a366-343665313731/sun.jpg",
            "Важно | Правила посадки и депозиты по зонам | Столы от 8 гостей, отдельные условия для VIP и веранды, плюс понятный тайминг брони. | https://static.tildacdn.com/tild3931-3739-4033-b630-636538666662/DSC03966_resized.jpg",
        ),
        "menu_highlights_text": _lines(
            "Hookah menu | Отдельный таб с кальянной картой и lounge-подачей.",
            "Авторская кухня | Китайская, итальянская, японская, американская, русская и европейская кухни.",
            "Soft drinks | Безалкогольный блок внутри меню вынесен отдельно.",
            "Alcoholic drinks | Два контактных бара и отдельный алкогольный раздел.",
        ),
        "service_cards_text": _lines(
            "Открыть заведение | Быстрый вход в сайт, бронь и loyalty-карту. | https://hp-vdnh.ru/",
            "Открыть меню | Сразу посмотреть кухню, бар и кальянные разделы. | https://hp-vdnh.ru/menu",
            "Правила и депозит | VIP, веранда и условия посадки по зонам. | https://hp-vdnh.ru/rules",
            "Позвонить | +7 495 108-27-07 | tel://74951082707",
        ),
    },
    "hookahplace_studio": {
        "tagline": "Lounge в Крылатском с живой музыкой, парковкой и большими спортивными трансляциями.",
        "summary": "По официальной странице HookahPlace Studio это московский lounge на Осеннем бульваре, где делают ставку на хороший кальянный отдых, живую музыку, DJ-сеты и трансляции матчей на большом проекторе. Для `Места` это полезный сценарий не только «куда зайти рядом», но и «куда идти под вечер и компанию».",
        "logo_image_url": "",
        "hero_image_url": "",
        "venue_address": "Москва, Осенний бульвар, 10",
        "venue_hours": "Пн-Чт, Вс 12:00-01:00 · Пт-Сб 12:00-04:00",
        "venue_price": "по брони",
        "venue_format": "живая музыка · проектор · парковка",
        "venue_phone": "+7 926 726-73-73",
        "venue_booking_url": "https://hookahplace.ru/places/hookahplace-studio/",
        "venue_menu_url": "",
        "venue_loyalty_title": "",
        "venue_loyalty_summary": "",
        "highlights_text": _lines("Музыка", "Парковка", "Проектор"),
        "articles_text": _lines(
            "Новости | Живая музыка и вечерние сеты | Студия делает акцент не только на кальянах, но и на лайв-музыке, DJ и живом вечернем ритме. | ",
            "Формат | Матчи на большом проекторе | Трансляции хоккея и футбола делают место понятным выбором под компанию и long-session формат. | ",
        ),
        "menu_highlights_text": _lines(
            "Живая музыка | Лайв-выступления, DJ и вечерний lounge-ритм.",
            "Парковка | Удобно заезжать на машине и не думать о долгом вечернем сценарии.",
            "Большой экран | Хоккей и футбол на проекторе под компанию и кальян.",
        ),
        "service_cards_text": _lines(
            "Открыть заведение | Карточка lounge с адресом, часами работы и входом в бронь. | https://hookahplace.ru/places/hookahplace-studio/",
            "Позвонить | +7 926 726-73-73 | tel://79267267373",
        ),
    },
    "hookahplace_urban": {
        "tagline": "Городской lounge на Одесской с кухней, видеоиграми и быстрым сценарием после работы.",
        "summary": "По официальной странице HookahPlace Urban это городской московский lounge на Одесской, где есть кухня, напитки, Wi‑Fi и видеоигры. Для вкладки `Места` это хороший utilitarian place: близко, понятно, без лишней мистики, с быстрым входом в бронь и меню.",
        "logo_image_url": "",
        "hero_image_url": "",
        "venue_address": "Москва, Одесская улица, 2",
        "venue_hours": "Пн-Чт 11:00-00:00 · Пт 11:00-02:00 · Сб 13:00-02:00 · Вс 13:00-00:00",
        "venue_price": "по брони",
        "venue_format": "кухня · видеоигры · city lounge",
        "venue_phone": "+7 900 555-44-33",
        "venue_booking_url": "https://hookahplace.ru/places/hookahplace-urban/",
        "venue_menu_url": "https://hpurban.ru",
        "venue_loyalty_title": "",
        "venue_loyalty_summary": "",
        "highlights_text": _lines("Кухня", "Видеоигры", "Рядом после работы"),
        "articles_text": _lines(
            "Формат | Городской формат без перегруза | Urban собирает вокруг себя удобный сценарий: кухня, напитки, игры и быстрая бронь. | ",
        ),
        "menu_highlights_text": _lines(
            "Есть кухня | Не только кальян, но и полноценный городской сценарий с едой.",
            "Видеоигры | Подходит для короткого визита, компании и after-work формата.",
            "Быстрый вход | Понятный utilitarian lounge без лишней усложнённой подачи.",
        ),
        "service_cards_text": _lines(
            "Открыть заведение | Карточка места с бронью и часами работы. | https://hookahplace.ru/places/hookahplace-urban/",
            "Сайт Urban | Быстрый вход на отдельный сайт заведения. | https://hpurban.ru",
            "Позвонить | +7 900 555-44-33 | tel://79005554433",
        ),
    },
    "hookahplace_rockstar": {
        "tagline": "Тематический rock’n’roll lounge на Сухаревской с кухней, напитками и сильным характером пространства.",
        "summary": "По официальной странице HookahPlace RockStar это концептуальный lounge в центре Москвы, где рок-н-ролльный интерьер, барная карта, китайские чаи и кальяны собраны в один узнаваемый сценарий. Для `Места` это отличный кейс того, как рекомендовать не просто район, а атмосферу.",
        "logo_image_url": "",
        "hero_image_url": "",
        "venue_address": "Москва, Большой Сухаревский переулок, 5с2",
        "venue_hours": "Пн-Чт, Вс 14:00-02:00 · Пт-Сб 14:00-04:00",
        "venue_price": "по брони",
        "venue_format": "центр · кухня · bar lounge",
        "venue_phone": "+7 495 145-88-28",
        "venue_booking_url": "https://hookahplace.ru/places/hookahplace-rockstar/",
        "venue_menu_url": "",
        "venue_loyalty_title": "",
        "venue_loyalty_summary": "",
        "highlights_text": _lines("Концепт", "Центр", "Кухня"),
        "articles_text": _lines(
            "Новости | Концептуальный lounge в центре | Кирпич, бетон, красный бархат и рок-н-ролл делают место не про сервисный минимум, а про атмосферу. | ",
            "Меню | Бар, чаи и кальянный вечер | Барная карта и китайские чаи усиливают сценарий долгого вечернего отдыха. | ",
        ),
        "menu_highlights_text": _lines(
            "Rock’n’roll vibe | Сильный характер пространства и понятный вечерний сценарий.",
            "Бар и китайские чаи | Место работает не только как кальянная, но и как барный lounge.",
            "Центр Москвы | Легко положить в подборки по району и quick-night plans.",
        ),
        "service_cards_text": _lines(
            "Открыть заведение | Карточка lounge с бронью, адресом и форматом. | https://hookahplace.ru/places/hookahplace-rockstar/",
            "Позвонить | +7 495 145-88-28 | tel://74951458828",
        ),
    },
    "myata_tulskaya": {
        "tagline": "Сетевой lounge на Тульской с DJ, VIP-комнатами, кухней, PlayStation 5 и loyalty-логикой Мяты.",
        "summary": "По официальной странице Мята Тульская это lounge на Духовском переулке с кухней, VIP-комнатами, PS5, парковкой и событийной программой. На уровне продукта это полезный пример сетевого lounge, где recommendation может опираться не только на место, но и на понятную loyalty-систему бренда.",
        "logo_image_url": "",
        "hero_image_url": "",
        "venue_address": "Москва, Духовской переулок, 17с16",
        "venue_hours": "Пн-Чт, Вс 12:00-01:00 · Пт-Сб 14:00-04:00",
        "venue_price": "по брони",
        "venue_format": "VIP · DJ · кухня · сеть",
        "venue_phone": "+7 977 138-70-07",
        "venue_booking_url": "https://myataofficial.com/place/tulskaya",
        "venue_menu_url": "https://myataofficial.com/place/tulskaya",
        "venue_loyalty_title": "Мята Loyalty",
        "venue_loyalty_summary": "Сетевой loyalty-слой Мяты: welcome-баллы, кешбэк, рост уровня и возможность оплачивать часть счёта бонусами.",
        "highlights_text": _lines("Loyalty", "VIP", "Сетевой lounge"),
        "articles_text": _lines(
            "Новости | DJ, вечеринки и событийный ритм | Место работает не только как lounge, но и как событийная точка с понятным evening-loop. | ",
            "Акции | Loyalty-система сети Мята | Сетевая логика с баллами и привилегиями делает это место хорошим кейсом для вкладки `Места`. | ",
        ),
        "menu_highlights_text": _lines(
            "VIP и сервис | VIP-комнаты и более длинный вечерний сценарий под компанию.",
            "PlayStation 5 | Подходит под компанию и social lounge usage.",
            "Мята Loyalty | Привилегии и накопительная логика сети, понятная пользователю.",
        ),
        "service_cards_text": _lines(
            "Открыть заведение | Официальная карточка lounge с бронью и услугами. | https://myataofficial.com/place/tulskaya",
            "Открыть карточку Мяты | Меню, новости и услуги заведения внутри сети. | https://myataofficial.com/place/tulskaya",
            "Позвонить | +7 977 138-70-07 | tel://79771387007",
        ),
    },
}

